# fly.toml app configuration file generated for wild-moon-2912 on 2023-05-19T13:00:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-moon-2912"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
